### ISSUE TITLE
Investigate: Ingestion-time vs Query-time linking

### ISSUE THREAD

**Issue by vackosar** [AbsaOSS/spline#102]

**Comment by wajda** [comment]
If I get it right the main motivation for this issue is lacking offset information on streaming operations, so we don;t know how to link stuff properly on the ingestion time. In my understanding doing it on query time won't help as there is no way for the missing bits of the lineage information to come later and refine the existing data. So from this perspective we could simply connect the nodes on the best effort basis on the ingestion time and the result would be the same as if you join it on the quire time.

Thinking about it more in general the query time linking isn't really an option for us at all, as it defeats the whole purpose of a graph storage. By choosing graph model we want to avoid joins at query time in the first place, and rather maintain the persisted graph as complete as possible at all times.

**Comment by vackosar** [comment]
We used different definition of linking. Linking in terms of connecting parent-child lineages based on lineage of specific data will be done on query time. While all lineages will be connected to common data source URIs as URIs are unique.
