### ISSUE TITLE
Investigate: mongo incremental migrations vs lineage message streaming

### ISSUE THREAD

**Issue by vackosar** [AbsaOSS/spline#104]
How to ensure latest data in the Spline 0.4?

**Comment by wajda** [comment]
Since in 0.4 we won't have new agents yet we'll let users to continue using 0.3 agents writing to MongoDB. So the only way how 0.4 can get the data in is via the incremental migration. One way of doing it is reading MongoDB oplog maintaining the last processed offset. Another way, although not the most efficient and probably much slower (depends on how much data we have in Mongo), but perhaps the easiest to implement - is to periodically run the migrator tool and simply skip already imported lineages. This would be easy to do as in mongoDB we store lineages as aggregates. So before starting processing the next lineage it's enough to simply check if there is a job with this UID in Arrango already, and if there is one just skip the entire lineage.

**Comment by vackosar** [comment]
I will try to use Change Streams that are a wrapper above Oplog and see how that works out.
https://docs.mongodb.com/manual/changeStreams/
