### ISSUE TITLE
Delete older or unusable execution events

### ISSUE THREAD

**Issue by petergomez97** [AbsaOSS/spline#1258]
Is it possible to delete older executionexecution events or the ones that are not usable? We have hundreds of jobs in our company and we do not want unnecessary executions.

**Comment by petergomez97** [comment]
And what would be the most efficient way to do it?

**Comment by wajda** [comment]
In the version 1.0.0, we have added the the `db-prune` command to the Spline Admin tool with ability to specify the max age or a threshold date for the execution plans you want to keep. See #684
Unfortunately the version is still under development, and there were no active development in Spline for several months due to lack of resources and temporary change of priorities for the team. I expect things to improve soon, but cannot give you any reliable ETA. I personally hope we'll be able to resume work and release 1.0.0 closer to the end of the year, but not earlier than October 2023

**Comment by wajda** [comment]
Closing as a duplicate for #684

**Comment by petergomez97** [comment]
Thanks for the response, really appreciate the quickness and that this issue is included in the roadmap.
