### ISSUE TITLE
Spline Admin - replication factor set to 1

### ISSUE THREAD

**Issue by cerveada** [AbsaOSS/spline#1296]
When run on an internal Kubernetes cluster, the arangoDb collections have replication factor set to one even though they are spread on three nodes. In this situation, replication factor should be at least two to be able to tolerate failure of one node.

Investigate Admin CLI, find out why this happened and make sure the replication factor is set correctly next time.

This is set on per collection bases
https://docs.arangodb.com/3.11/develop/http-api/collections/#create-a-collection_body_replicationFactor

**Comment by wajda** [comment]
This issue is only relevant with respect to Admin CLI versions prior to 1.0, as in the 1.0 there is a CLI option to set the replication factor for all or separate collections. https://github.com/AbsaOSS/spline/blob/fce1edfb4b9fbafa1b36f18efc4f9074ab7500cd/admin/src/main/scala/za/co/absa/spline/admin/AdminCLI.scala#L176
