### ISSUE TITLE
MongoDB 4.0 support

### ISSUE THREAD

**Issue by Kazudo** [AbsaOSS/spline#297]
I was wondering if there's any plans on supporting MongoDB 4.0+ in the near future.

**Comment by wajda** [comment]
We didn't test Spline against MongoDB 4.0 specifically, but we received a feedback that Spline 0.3.8 works with it without any issues.
Regarding the future plans, Spline 0.3 is now on a maintenance, so we don't plan any significant changes in it. And upcoming Spline 0.4 will use ArangoDB instead of Mongo.

**Comment by Kazudo** [comment]
Ok thank you very much for your help
