### ISSUE TITLE
When migrating from mongodb to arangodb a non-existent source results in suspenseful migration

### ISSUE THREAD

**Issue by benedeki** [AbsaOSS/spline#329]
When migrating from _mongodb_ to _arangodb_ and the source _mongodb_ does not exists the migration ends claiming success, with 0 records migrated.
An actual error seems more appropriate and what one would expect.

**Comment by wajda** [comment]
Fixed in #342.
When querying data from a non-existing MongoDB it doesn't respond with an error, but returns an empty dataset as if there simply wasn't any data. Checking the actual existence of a database in MongoDB is a bit cumbersome. So, in the Migrator, instead of treating this case erroneous I simply put a warning there. I think it serves the purpose.
```
Processed: 0         Failures: 0         Speed [doc/sec]: 0.00      Load: [.....]
WARNING. No records found.
```
