### ISSUE TITLE
Spline Atlas integration

### ISSUE THREAD

**Issue by iamgzy** [AbsaOSS/spline#337]
I have two questions regarding Spline Atlas integration

1. Deployed on HDP 2.6.5, I can see Spark job lineage on DETAILS, which input/output/datasets/operation information showing on a table, but no lineage chart displayed (basically the LINEAGE & IMPACT section is folded) if I chose Spark_Job from Atlas

Here are current version of associated components

> Spark2: 2.3.0
> Atlas 0.8.0
> Kafka 1.0.0
> HBase 1.1.2
> Solr 5.5.2.2.5

Is it normal? I also tried to deploy same application on Atlas from HDP 3.0.1 sandbox and basically the same result, LINEAGE tab is hidden on Spark_job and other Spark related models in Atlas

2. Is it possible to keep two spline persistence data store for Spline at run time? So lineage information will be persisted in both MongoDB and Atlas/HBase. 

2.1.  The reason for this request is we really love the UI from Spline Web UI tool and because of issue above (no column lineage or any lineage chart shown up in Atlas), we'd like to use Spline Web UI for the UI presentation but still want to persist lineage info in Atlas/HBase, so that can be integrated along with Hive lineage in Atlas

2.2.  If the answer is no, can Spline-Web-UI work on top of HBase instead of MongoDB so that HBase becomes the datastore for lineage and Spline-Web-UI can work on top of it (using only one metadata store instead of two).

Thanks in advance.

**Comment by wajda** [comment]
Hi @iamgzy ,

1. For the Atlas related questions you can try to reach out to @mn-mikke, he's the guy who implemented it.  Also we decided to drop the support for Atlas in the next Spline version. We still have yet to decide if we want to re-introduce Atlas support in the future, or to make Spline featureful enough to make Altas integration redundant. See #279 

2. Regarding using several data stores in parallel - yes, it's possible.  You can use `za.co.absa.spline.persistence.api.composition.ParallelCompositeFactory` as your persistence factory. And then add `spline.persistence.composition.factories` property with a comma separated list of fully specified class names of the target persistence factories that you want to use in parallel. For example:
```properties
spline.persistence.factory=za.co.absa.spline.persistence.api.composition.ParallelCompositeFactory
spline.persistence.composition.factories=za.co.absa.spline.persistence.mongo.MongoPersistenceFactory,za.co.absa.spline.persistence.atlas.AtlasPersistenceFactory
```

2.1. Exactly! The ability to store the lineage data in several places at once was specifically added to cover the case, when you different lineage aspects are seen better in different tools. Spline as PoC doesn't mean to provide full featured UI to all users out of the box. That's also why we added Atlas support to the earlier Spline version - to try out different ways of presenting the data. In the new Spline concept we will continue providing this flexibility, but in another way. Instead of allowing for different types of data stores we will provide different kinds of API to query the stored data.

2.2. No, Spline don't support HBase as a primary data store. However it can be implemented as an external library and easily used in Spline. In Spline 0.3 persistence API is designed to allow for any kind of storage. You can use MongoPersistenceFactory as an example.

**Comment by iamgzy** [comment]
> Hi @iamgzy ,
> 
> 1. For the Atlas related questions you can try to reach out to @mn-mikke, he's the guy who implemented it.  Also we decided to drop the support for Atlas in the next Spline version. We still have yet to decide if we want to re-introduce Atlas support in the future, or to make Spline featureful enough to make Altas integration redundant. See #279
> 2. Regarding using several data stores in parallel - yes, it's possible.  You can use `za.co.absa.spline.persistence.api.composition.ParallelCompositeFactory` as your persistence factory. And then add `spline.persistence.composition.factories` property with a comma separated list of fully specified class names of the target persistence factories that you want to use in parallel. For example:
> 
> ```ini
> spline.persistence.factory=za.co.absa.spline.persistence.api.composition.ParallelCompositeFactory
> spline.persistence.composition.factories=za.co.absa.spline.persistence.mongo.MongoPersistenceFactory,za.co.absa.spline.persistence.atlas.AtlasPersistenceFactory
> ```
> 
> 2.1. Exactly! The ability to store the lineage data in several places at once was specifically added to cover the case, when you different lineage aspects are seen better in different tools. Spline as PoC doesn't mean to provide full featured UI to all users out of the box. That's also why we added Atlas support to the earlier Spline version - to try out different ways of presenting the data. In the new Spline concept we will continue providing this flexibility, but in another way. Instead of allowing for different types of data stores we will provide different kinds of API to query the stored data.
> 
> 2.2. No, Spline don't support HBase as a primary data store. However it can be implemented as an external library and easily used in Spline. In Spline 0.3 persistence API is designed to allow for any kind of storage. You can use `MongoPersistenceFactory` as an example.

@wajda  @mn-mikke
Thanks much for the thorough reply, that helped a lot! We sincerely hope Atlas integration can still remain in the newer release, it helped a lot (will comment on that new thread too)

Thanks again !
