### ISSUE TITLE
Read lineage.json to be able to re-run a job against same data

### ISSUE THREAD

**Issue by mehd-io** [AbsaOSS/spline#54]
Hi there,

Thx for the project, first hands on looks nice.

For certain data pipeline, we need to be able to run a job against same previous data.
Our spark job contains a `.conf` file that point to our dataset inputs.

The problem is how do I make a link between the df read in the conf file and the input id from the lineage.json.

The problem is that if I store my dataframe in a `val`, I wont see that name in the logicalPlan right ?
Is it possible to extend easily the metadata written in .json ?
Whats the best way to proceed then ?

Thx!

**Comment by wajda** [comment]
Hi Mehdi,
I'm not sure I understand your question. Can you explain it better?

Regarding `val`'s. You don't see them in a lineage because they are not captured. Spline only sees the resulted logical plan the way Spark sees it. It doesn't do any static analysis of your Spark app source code to capture intermediate steps like variables and methods.
