### ISSUE TITLE
Can you publish 0.5.2 rest gateway and client war file

### ISSUE THREAD

**Issue by uday1409** [AbsaOSS/spline#683]
## Background [Optional]
A clear explanation of the reason for raising the question. 
This gives us a better understanding of your use cases and how we might accommodate them.

## Question
A clear and concise inquiry

**Comment by wajda** [comment]
There is no need to. The latest server version is 0.5.1. Since Spline 0.5 the server and the agent are loosely coupled projects and have their own release cycles. We'll follow the best principles of the _Semantic Versioning_ to ensure API compatibility for the minor version numbers at least.
So generally speaking, grab the latest components you can find and you are good to go.

**Comment by wajda** [comment]
http://10.2.20.24:8080/producer looks correct.
To verify that it's actually running try this:
```shell
curl --get http://10.2.20.24:8080/about/version
curl --help http://10.2.20.24:8080/producer/status
```
