### ISSUE TITLE
ArangoDB: Errors in a cluster environment

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline#761]
```
java.util.concurrent.CompletionException: com.arangodb.ArangoDBException: Response: 500, Error: 1521 - AQL: collection not known to traversal: 'operation'. please add 'WITH operation' as the first line in your AQL (while executing)
```

from the ArangoDB [docs](https://www.arangodb.com/docs/stable/aql/operations-with.html)
> From ArangoDB 3.1 onwards **WITH is required** for traversals **in a clustered environment** in order to avoid deadlocks.

**Comment by wajda** [comment]
@lokm01

**Comment by lokm01** [comment]
Thanks 👍

**Comment by wajda** [comment]
@lokm01 could you please try the above PR? DB re-creation is required.

**Comment by lokm01** [comment]
So this loads the lineage list, but fails to load the lineage overview, see:

`2020-08-19T08:58:38.927+02:00 | 06:58:38.927 [http-nio-8080-exec-9] ERROR z.c.a.s.common.logging.ErrorCode$ - ErrorCode(144120c9-4ffc-4aae-9f09-4aced4317111)
  | 2020-08-19T08:58:38.927+02:00 | java.util.concurrent.CompletionException: com.arangodb.ArangoDBException: Response: 500, Error: 1583 - AQL: in function 'SPLINE::EVENT_LINEAGE_OVERVIEW()': user function runtime error: ArangoError: AQL: illegal AQL transaction state (exception location: /work/ArangoDB/arangod/Cluster/ClusterTrxMethods.cpp:400). Please report this error to arangodb.com (while optimizing plan)
  | 2020-08-19T08:58:38.927+02:00 | at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:84:16)
  | 2020-08-19T08:58:38.927+02:00 | at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:102:45)
  | 2020-08-19T08:58:38.927+02:00 | at Object.callback ((user function SPLINE::EVENT_LINEAGE_OVERVIEW):1:2216)
  | 2020-08-19T08:58:38.927+02:00 | at exports.FCALL_USER (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:182:55)
  | 2020-08-19T08:58:38.927+02:00 | stacktrace of offending AQL function: ArangoError: in function 'SPLINE::EVENT_LINEAGE_OVERVIEW()': user function runtime error: ArangoError: AQL: illegal AQL transaction state (exception location: /work/ArangoDB/arangod/Cluster/ClusterTrxMethods.cpp:400). Please report this error to arangodb.com (while optimizing plan)
  | 2020-08-19T08:58:38.927+02:00 | at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:84:16)
  | 2020-08-19T08:58:38.927+02:00 | at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:102:45)
  | 2020-08-19T08:58:38.927+02:00 | at Object.callback ((user function SPLINE::EVENT_LINEAGE_OVERVIEW):1:2216)
  | 2020-08-19T08:58:38.927+02:00 | at exports.FCALL_USER (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:182:55)
  | 2020-08-19T08:58:38.927+02:00 | at THROW (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:45:13)
  | 2020-08-19T08:58:38.927+02:00 | at exports.FCALL_USER (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:184:5) (while executing)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
  | 2020-08-19T08:58:38.927+02:00 | at com.arangodb.async.internal.velocystream.VstCommunicationAsync.lambda$execute$0(VstCommunicationAsync.java:66)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
  | 2020-08-19T08:58:38.927+02:00 | at com.arangodb.async.internal.velocystream.VstConnectionAsync.lambda$write$0(VstConnectionAsync.java:48)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | 2020-08-19T08:58:38.927+02:00 | at com.arangodb.internal.velocystream.internal.MessageStore.consume(MessageStore.java:62)
  | 2020-08-19T08:58:38.927+02:00 | at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:65)
  | 2020-08-19T08:58:38.927+02:00 | at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:59)
  | 2020-08-19T08:58:38.927+02:00 | at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:151)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | 2020-08-19T08:58:38.927+02:00 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | 2020-08-19T08:58:38.927+02:00 | at java.lang.Thread.run(Thread.java:748)
  | 2020-08-19T08:58:38.927+02:00 | Caused by: com.arangodb.ArangoDBException: Response: 500, Error: 1583 - AQL: in function 'SPLINE::EVENT_LINEAGE_OVERVIEW()': user function runtime error: ArangoError: AQL: illegal AQL transaction state (exception location: /work/ArangoDB/arangod/Cluster/ClusterTrxMethods.cpp:400). Please report this error to arangodb.com (while optimizing plan)
  | 2020-08-19T08:58:38.927+02:00 | at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:84:16)
  | 2020-08-19T08:58:38.927+02:00 | at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:102:45)
  | 2020-08-19T08:58:38.927+02:00 | at Object.callback ((user function SPLINE::EVENT_LINEAGE_OVERVIEW):1:2216)
  | 2020-08-19T08:58:38.927+02:00 | at exports.FCALL_USER (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:182:55)
  | 2020-08-19T08:58:38.927+02:00 | stacktrace of offending AQL function: ArangoError: in function 'SPLINE::EVENT_LINEAGE_OVERVIEW()': user function runtime error: ArangoError: AQL: illegal AQL transaction state (exception location: /work/ArangoDB/arangod/Cluster/ClusterTrxMethods.cpp:400). Please report this error to arangodb.com (while optimizing plan)
  | 2020-08-19T08:58:38.927+02:00 | at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:84:16)
  | 2020-08-19T08:58:38.927+02:00 | at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:102:45)
  | 2020-08-19T08:58:38.927+02:00 | at Object.callback ((user function SPLINE::EVENT_LINEAGE_OVERVIEW):1:2216)
  | 2020-08-19T08:58:38.927+02:00 | at exports.FCALL_USER (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:182:55)
  | 2020-08-19T08:58:38.927+02:00 | at THROW (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:45:13)
  | 2020-08-19T08:58:38.927+02:00 | at exports.FCALL_USER (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:184:5) (while executing)
  | 2020-08-19T08:58:38.927+02:00 | ... 15 common frames omitted
  | 2020-08-19T10:07:47.198+02:00 | 08:07:47.198 [http-nio-8080-exec-4] ERROR z.c.a.s.common.logging.ErrorCode$ - ErrorCode(b139b818-b274-4ce5-abc6-a5a4baa4f5d8)
  | 2020-08-19T10:07:47.198+02:00 | java.util.concurrent.CompletionException: com.arangodb.ArangoDBException: Response: 500, Error: 1583 - AQL: in function 'SPLINE::EVENT_LINEAGE_OVERVIEW()': user function runtime error: ArangoError: AQL: illegal AQL transaction state (exception location: /work/ArangoDB/arangod/Cluster/ClusterTrxMethods.cpp:400). Please report this error to arangodb.com (while optimizing plan)
  | 2020-08-19T10:07:47.198+02:00 | at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:84:16)
  | 2020-08-19T10:07:47.198+02:00 | at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:102:45)
  | 2020-08-19T10:07:47.198+02:00 | at Object.callback ((user function SPLINE::EVENT_LINEAGE_OVERVIEW):1:2216)
  | 2020-08-19T10:07:47.198+02:00 | at exports.FCALL_USER (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:182:55)
  | 2020-08-19T10:07:47.198+02:00 | stacktrace of offending AQL function: ArangoError: in function 'SPLINE::EVENT_LINEAGE_OVERVIEW()': user function runtime error: ArangoError: AQL: illegal AQL transaction state (exception location: /work/ArangoDB/arangod/Cluster/ClusterTrxMethods.cpp:400). Please report this error to arangodb.com (while optimizing plan)
  | 2020-08-19T10:07:47.198+02:00 | at ArangoStatement.execute (/usr/share/arangodb3/js/server/modules/@arangodb/arango-statement.js:84:16)
  | 2020-08-19T10:07:47.198+02:00 | at ArangoDatabase._query (/usr/share/arangodb3/js/server/modules/@arangodb/arango-database.js:102:45)
  | 2020-08-19T10:07:47.198+02:00 | at Object.callback ((user function SPLINE::EVENT_LINEAGE_OVERVIEW):1:2216)
  | 2020-08-19T10:07:47.198+02:00 | at exports.FCALL_USER (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:182:55)
  | 2020-08-19T10:07:47.198+02:00 | at THROW (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:45:13)
  | 2020-08-19T10:07:47.198+02:00 | at exports.FCALL_USER (/usr/share/arangodb3/js/server/modules/@arangodb/aql.js:184:5) (while executing)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:326)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:338)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.CompletableFuture.uniRelay(CompletableFuture.java:925)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:913)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
  | 2020-08-19T10:07:47.198+02:00 | at com.arangodb.async.internal.velocystream.VstCommunicationAsync.lambda$execute$0(VstCommunicationAsync.java:66)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:750)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
  | 2020-08-19T10:07:47.198+02:00 | at com.arangodb.async.internal.velocystream.VstConnectionAsync.lambda$write$0(VstConnectionAsync.java:48)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | 2020-08-19T10:07:47.198+02:00 | at com.arangodb.internal.velocystream.internal.MessageStore.consume(MessageStore.java:62)
  | 2020-08-19T10:07:47.198+02:00 | at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:65)
  | 2020-08-19T10:07:47.198+02:00 | at com.arangodb.internal.velocystream.internal.ChunkStore.checkCompleteness(ChunkStore.java:59)
  | 2020-08-19T10:07:47.198+02:00 | at com.arangodb.internal.velocystream.internal.VstConnection.lambda$open$0(VstConnection.java:151)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | 2020-08-19T10:07:47.198+02:00 | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | 2020-08-19T10:07:47.198+02:00 | at java.lang.Thread.run(Thread.java:748)`

**Comment by wajda** [comment]
Seems like we have to find an alternative to AQL UDFs - https://github.com/arangodb/arangodb/issues/11271

**Comment by wajda** [comment]
[Foxx microservices](https://www.arangodb.com/docs/stable/foxx.html) seems to be a solution. We need to replace our UDFs with a Foxx service.

**Comment by wajda** [comment]
FYI - https://github.com/arangodb/arangodb-java-driver/issues/357
